git:
  submodules: false
language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    emulator/verilator
    riscy/target/resolution-cache

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

env:
  matrix:
    - MODULE=HelloModule
    - MODULE=RegFile
    - MODULE=Fetch

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8

script:
  - make -C riscy ${MODULE}.test

before_cache:
  - ls -tr regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf

notifications:
  slack: cs752-rocketchip:Z5AFrgVOYg2ERuMxLZoamT3W
