git:
  submodules: false
language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    emulator/verilator

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

env:
  matrix:
      #    - SUITE=RocketSuite
      #    - SUITE=GroundtestSuite
      #    - SUITE=UnittestSuite
    - MODULE_GEN=riscy.HelloModuleGenerator
    - MODULE_GEN=riscy.DecodeGenerator
    - MODULE_GEN=riscy.AllocGenerator

# blacklist private branches
#branches:
#  except:
#    - hwacha
#    - boom
#    - hurricane

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8

script:
#  - make emulator-ndebug -C regression SUITE=$SUITE TORTURE_CONFIG=default
#  - make emulator-regression-tests -C regression SUITE=$SUITE TORTURE_CONFIG=default
  - make -C riscy MODULE_GEN=$MODULE_GEN test

before_cache:
  - ls -tr regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf

notifications:
  slack: cs752-rocketchip:Z5AFrgVOYg2ERuMxLZoamT3W
