git:
  submodules: false
language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    emulator/verilator
    riscy/target/resolution-cache

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

branches:
  only:
    - master

env:
  matrix:
    - MODULE=HelloModule.test
    - MODULE=Fetch.test
    - MODULE=Decode.test
    - MODULE=Alloc.test
    - MODULE=ROB.test
    - MODULE=RegFile.test
    - MODULE=OpDecode.test
    - MODULE=Hello.hex.bench

before_install:
  - export CXX=g++-4.8 CC=gcc-4.8

script:
  - make -C riscy ${MODULE}

before_cache:
  - ls -tr regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf

notifications:
  slack: cs752-rocketchip:Z5AFrgVOYg2ERuMxLZoamT3W
